title: Computational Methods
email: palmergi1@cardiff.ac.uk
description: >- # this means to ignore newlines until "baseurl:"
  A short MSc course introducing programming through Python.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
permalink: pretty
syntax_highlighter: rouge
future: true
